# Generated by Django 3.2.13 on 2022-07-05 22:44

import backend.core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', backend.core.models.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', backend.core.models.AutoUpdatedField(default=django.utils.timezone.now, editable=False)),
                ('firebase_auth_user_id', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_to_mailing_list', models.BooleanField(default=False)),
                ('has_unsubscribed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
