runtime: python39

app_engine_apis: true
instance_class: F2

env_variables:
  APPENGINE_URL: net-startupworx-bloxtest10.ew.r.appspot.com
  DJANGO_SETTINGS_MODULE: 'backend.settings_remote'

handlers:
  - url: /static/
    static_dir: static
    secure: always
    login: optional
    http_headers:
      Strict-Transport-Security: 'max-age=2592000; includeSubdomains'
      X-Content-Type-Options: 'nosniff'
      X-Frame-Options: 'DENY'
      X-XSS-Protection: '1; mode=block'

  - url: /.*
    script: auto
    secure: always
    login: optional
